In [23]:
import pandas as pd

In [24]:
df = pd.read_excel("todos_resultados_instantaneos.xlsx")

df

     Repetition  Dataset Imputer Métrica       SVM        RF        GB
0             0        1    MICE  Recall  0.666667  0.666667  0.666667
1             1        1    MICE  Recall  0.571429  0.714286  0.142857
2             2        1    MICE  Recall  0.571429  0.428571  0.714286
3             3        1    MICE  Recall  0.714286  0.857143  0.714286
4             4        1    MICE  Recall  0.500000  0.833333  0.833333
..          ...      ...     ...     ...       ...       ...       ...
415           0        4    MICE     AUC  0.830128  0.766026  0.714744
416           1        4    MICE     AUC  0.750000  0.714744  0.759615
417           2        4    MICE     AUC  0.570513  0.713141  0.644231
418           3        4    MICE     AUC  0.763975  0.732919  0.736025
419           4        4    MICE     AUC  0.736025  0.708075  0.706522

[420 rows x 7 columns]

In [25]:
df["Métrica"].unique()

array(['Recall', 'Specificity', 'AUC'], dtype=object)

In [26]:
grupos = df.groupby("Métrica")

df_AUC = grupos.get_group("AUC")
df_recall = grupos.get_group("Recall")
df_spe = grupos.get_group("Specificity")

display(df_AUC)
display(df_recall)
display(df_spe)

     Repetition  Dataset Imputer Métrica       SVM        RF        GB
50            0        2    Mean     AUC  0.868720  0.834051  0.829892
51            1        2    Mean     AUC  0.832903  0.847053  0.828928
52            2        2    Mean     AUC  0.853027  0.846069  0.851439
53            3        2    Mean     AUC  0.832178  0.864638  0.864130
54            4        2    Mean     AUC  0.851633  0.852761  0.826252
..          ...      ...     ...     ...       ...       ...       ...
415           0        4    MICE     AUC  0.830128  0.766026  0.714744
416           1        4    MICE     AUC  0.750000  0.714744  0.759615
417           2        4    MICE     AUC  0.570513  0.713141  0.644231
418           3        4    MICE     AUC  0.763975  0.732919  0.736025
419           4        4    MICE     AUC  0.736025  0.708075  0.706522

[140 rows x 7 columns]

     Repetition  Dataset Imputer Métrica       SVM        RF        GB
0             0        1    MICE  Recall  0.666667  0.666667  0.666667
1             1        1    MICE  Recall  0.571429  0.714286  0.142857
2             2        1    MICE  Recall  0.571429  0.428571  0.714286
3             3        1    MICE  Recall  0.714286  0.857143  0.714286
4             4        1    MICE  Recall  0.500000  0.833333  0.833333
..          ...      ...     ...     ...       ...       ...       ...
410           0        4   LPMD2  Recall  0.692308  0.538462  0.538462
411           1        4   LPMD2  Recall  0.692308  0.384615  0.384615
412           2        4   LPMD2  Recall  0.846154  0.769231  0.461538
413           3        4   LPMD2  Recall  0.571429  0.500000  0.571429
414           4        4   LPMD2  Recall  0.714286  0.571429  0.500000

[140 rows x 7 columns]

     Repetition  Dataset Imputer      Métrica       SVM        RF        GB
10            0        4  PMIVAE  Specificity  0.666667  0.791667  0.791667
11            1        4  PMIVAE  Specificity  0.833333  0.791667  0.833333
12            2        4  PMIVAE  Specificity  0.458333  0.500000  0.458333
13            3        4  PMIVAE  Specificity  0.652174  0.608696  0.739130
14            4        4  PMIVAE  Specificity  0.565217  0.521739  0.565217
..          ...      ...     ...          ...       ...       ...       ...
405           0        3  PMIVAE  Specificity  0.640884  0.701657  0.690608
406           1        3  PMIVAE  Specificity  0.596685  0.662983  0.624309
407           2        3  PMIVAE  Specificity  0.679558  0.635359  0.662983
408           3        3  PMIVAE  Specificity  0.722222  0.677778  0.655556
409           4        3  PMIVAE  Specificity  0.711111  0.700000  0.738889

[140 rows x 7 columns]

In [27]:
df_AUC_1 = df_AUC[["Repetition", "Dataset", "Imputer", "Métrica", "SVM"]]
df_AUC_1 = df_AUC_1.rename(columns={"SVM": "score"})
display(df_AUC_1)

df_AUC_2 = df_AUC[["Repetition", "Dataset", "Imputer", "Métrica", "RF"]]
df_AUC_2 = df_AUC_2.rename(columns={"RF": "score"})
display(df_AUC_2)

df_AUC_3 = df_AUC[["Repetition", "Dataset", "Imputer", "Métrica", "GB"]]
df_AUC_3 = df_AUC_3.rename(columns={"GB": "score"})
display(df_AUC_3)

     Repetition  Dataset Imputer Métrica     score
50            0        2    Mean     AUC  0.868720
51            1        2    Mean     AUC  0.832903
52            2        2    Mean     AUC  0.853027
53            3        2    Mean     AUC  0.832178
54            4        2    Mean     AUC  0.851633
..          ...      ...     ...     ...       ...
415           0        4    MICE     AUC  0.830128
416           1        4    MICE     AUC  0.750000
417           2        4    MICE     AUC  0.570513
418           3        4    MICE     AUC  0.763975
419           4        4    MICE     AUC  0.736025

[140 rows x 5 columns]

     Repetition  Dataset Imputer Métrica     score
50            0        2    Mean     AUC  0.834051
51            1        2    Mean     AUC  0.847053
52            2        2    Mean     AUC  0.846069
53            3        2    Mean     AUC  0.864638
54            4        2    Mean     AUC  0.852761
..          ...      ...     ...     ...       ...
415           0        4    MICE     AUC  0.766026
416           1        4    MICE     AUC  0.714744
417           2        4    MICE     AUC  0.713141
418           3        4    MICE     AUC  0.732919
419           4        4    MICE     AUC  0.708075

[140 rows x 5 columns]

     Repetition  Dataset Imputer Métrica     score
50            0        2    Mean     AUC  0.829892
51            1        2    Mean     AUC  0.828928
52            2        2    Mean     AUC  0.851439
53            3        2    Mean     AUC  0.864130
54            4        2    Mean     AUC  0.826252
..          ...      ...     ...     ...       ...
415           0        4    MICE     AUC  0.714744
416           1        4    MICE     AUC  0.759615
417           2        4    MICE     AUC  0.644231
418           3        4    MICE     AUC  0.736025
419           4        4    MICE     AUC  0.706522

[140 rows x 5 columns]

In [28]:
df_AUC = pd.concat([df_AUC_1, df_AUC_2, df_AUC_3],  ignore_index=True)
df_AUC.head()

   Repetition  Dataset Imputer Métrica     score
0           0        2    Mean     AUC  0.868720
1           1        2    Mean     AUC  0.832903
2           2        2    Mean     AUC  0.853027
3           3        2    Mean     AUC  0.832178
4           4        2    Mean     AUC  0.851633

In [29]:
df_AUC_pivot = df_AUC.pivot_table(index=["Repetition", "Dataset", "Métrica"], columns="Imputer", values="score")

df_AUC_pivot

Imputer                          KNN      LPMD     LPMD2      MICE      Mean  \
Repetition Dataset Métrica
0          1       AUC      0.793144  0.743203  0.721631  0.719858  0.774823
           2       AUC      0.835796  0.843044  0.824308  0.840312  0.844221
           3       AUC      0.774610  0.777286  0.628392  0.773463  0.775513
           4       AUC      0.763889  0.735043  0.820513  0.770299  0.740385
1          1       AUC      0.629544  0.633129  0.642857  0.601895  0.599334
           2       AUC      0.836126  0.833573  0.820447  0.838139  0.836295
           3       AUC      0.715001  0.725894  0.608204  0.729369  0.714636
           4       AUC      0.740385  0.744658  0.626068  0.741453  0.735043
2          1       AUC      0.735279  0.760369  0.672555  0.734255  0.796723
           2       AUC      0.840928  0.836333  0.850383  0.844962  0.850179
           3       AUC      0.726958  0.725721  0.677725  0.741068  0.733272
           4       AUC      0.629274  0.661859  0.558226  0.642628  0.665598
3          1       AUC      0.716334  0.718126  0.683308  0.733743  0.699181
           2       AUC      0.859569  0.841791  0.830181  0.845201  0.853648
           3       AUC      0.731639  0.730556  0.572554  0.738330  0.728346
           4       AUC      0.750518  0.703934  0.698758  0.744306  0.697205
4          1       AUC      0.650538  0.721027  0.695042  0.686081  0.729092
           2       AUC      0.840955  0.846000  0.814367  0.844989  0.843549
           3       AUC      0.769078  0.762884  0.646174  0.778564  0.765828
           4       AUC      0.741201  0.669772  0.719462  0.716874  0.643375

Imputer                       PMIVAE      SAEI
Repetition Dataset Métrica
0          1       AUC      0.729019  0.674941
           2       AUC      0.843696  0.854182
           3       AUC      0.774262  0.781056
           4       AUC      0.727564  0.736111
1          1       AUC      0.620328  0.590886
           2       AUC      0.832976  0.829934
           3       AUC      0.713715  0.732296
           4       AUC      0.752137  0.702991
2          1       AUC      0.738095  0.672299
           2       AUC      0.842853  0.840541
           3       AUC      0.729931  0.731667
           4       AUC      0.580128  0.683761
3          1       AUC      0.700461  0.677675
           2       AUC      0.852659  0.849176
           3       AUC      0.725393  0.728477
           4       AUC      0.691511  0.772257
4          1       AUC      0.733274  0.665173
           2       AUC      0.847446  0.853208
           3       AUC      0.760849  0.758718
           4       AUC      0.710145  0.746377

In [30]:
df_AUC_pivot_reset = df_AUC_pivot.reset_index()
df_AUC_pivot_reset.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df_AUC_pivot_reset.columns.values]
df_AUC_pivot_reset

,Repetition,Dataset,Métrica,KNN,LPMD,LPMD2,MICE,Mean,PMIVAE,SAEI
0,0,1,AUC,0.793144,0.743203,0.721631,0.719858,0.774823,0.729019,0.674941
1,0,2,AUC,0.835796,0.843044,0.824308,0.840312,0.844221,0.843696,0.854182
2,0,3,AUC,0.774610,0.777286,0.628392,0.773463,0.775513,0.774262,0.781056
3,0,4,AUC,0.763889,0.735043,0.820513,0.770299,0.740385,0.727564,0.736111
4,1,1,AUC,0.629544,0.633129,0.642857,0.601895,0.599334,0.620328,0.590886
5,1,2,AUC,0.836126,0.833573,0.820447,0.838139,0.836295,0.832976,0.829934
6,1,3,AUC,0.715001,0.725894,0.608204,0.729369,0.714636,0.713715,0.732296
7,1,4,AUC,0.740385,0.744658,0.626068,0.741453,0.735043,0.752137,0.702991
8,2,1,AUC,0.735279,0.760369,0.672555,0.734255,0.796723,0.738095,0.672299
9,2,2,AUC,0.840928,0.836333,0.850383,0.844962,0.850179,0.842853,0.840541
10,2,3,AUC,0.726958,0.725721,0.677725,0.741068,0.733272,0.729931,0.731667
11,2,4,AUC,0.629274,0.661859,0.558226,0.642628,0.665598,0.580128,0.683761
12,3,1,AUC,0.716334,0.718126,0.683308,0.733743,0.699181,0.700461,0.677675
13,3,2,AUC,0.859569,0.841791,0.830181,0.845201,0.853648,0.852659,0.849176
14,3,3,AUC,0.731639,0.730556,0.572554,0.738330,0.728346,0.725393,0.728477
15,3,4,AUC,0.750518,0.703934,0.698758,0.744306,0.697205,0.691511,0.772257
16,4,1,AUC,0.650538,0.721027,0.695042,0.686081,0.729092,0.733274,0.665173
17,4,2,AUC,0.840955,0.846000,0.814367,0.844989,0.843549,0.847446,0.853208
18,4,3,AUC,0.769078,0.762884,0.646174,0.778564,0.765828,0.760849,0.758718
19,4,4,AUC,0.741201,0.669772,0.719462,0.716874,0.643375,0.710145,0.746377

In [31]:
df_AUC = df_AUC_pivot_reset[['KNN', 'LPMD', 'LPMD2', 'MICE', 'Mean', 'PMIVAE', 'SAEI']]
df_AUC

         KNN      LPMD     LPMD2      MICE      Mean    PMIVAE      SAEI
0   0.793144  0.743203  0.721631  0.719858  0.774823  0.729019  0.674941
1   0.835796  0.843044  0.824308  0.840312  0.844221  0.843696  0.854182
2   0.774610  0.777286  0.628392  0.773463  0.775513  0.774262  0.781056
3   0.763889  0.735043  0.820513  0.770299  0.740385  0.727564  0.736111
4   0.629544  0.633129  0.642857  0.601895  0.599334  0.620328  0.590886
5   0.836126  0.833573  0.820447  0.838139  0.836295  0.832976  0.829934
6   0.715001  0.725894  0.608204  0.729369  0.714636  0.713715  0.732296
7   0.740385  0.744658  0.626068  0.741453  0.735043  0.752137  0.702991
8   0.735279  0.760369  0.672555  0.734255  0.796723  0.738095  0.672299
9   0.840928  0.836333  0.850383  0.844962  0.850179  0.842853  0.840541
10  0.726958  0.725721  0.677725  0.741068  0.733272  0.729931  0.731667
11  0.629274  0.661859  0.558226  0.642628  0.665598  0.580128  0.683761
12  0.716334  0.718126  0.683308  0.733743  0.699181  0.700461  0.677675
13  0.859569  0.841791  0.830181  0.845201  0.853648  0.852659  0.849176
14  0.731639  0.730556  0.572554  0.738330  0.728346  0.725393  0.728477
15  0.750518  0.703934  0.698758  0.744306  0.697205  0.691511  0.772257
16  0.650538  0.721027  0.695042  0.686081  0.729092  0.733274  0.665173
17  0.840955  0.846000  0.814367  0.844989  0.843549  0.847446  0.853208
18  0.769078  0.762884  0.646174  0.778564  0.765828  0.760849  0.758718
19  0.741201  0.669772  0.719462  0.716874  0.643375  0.710145  0.746377

In [32]:
df_AUC.to_csv("df_AUC_real_datasets.csv", index=False)

# Refazendo procedimento para RECALL

In [33]:
df_rec_1 = df_recall[["Repetition", "Dataset", "Imputer", "Métrica", "SVM"]]
df_rec_1 = df_rec_1.rename(columns={"SVM": "score"})
display(df_rec_1)

df_rec_2 = df_recall[["Repetition", "Dataset", "Imputer", "Métrica", "RF"]]
df_rec_2 = df_rec_2.rename(columns={"RF": "score"})
display(df_rec_2)

df_rec_3 = df_recall[["Repetition", "Dataset", "Imputer", "Métrica", "GB"]]
df_rec_3 = df_rec_3.rename(columns={"GB": "score"})
display(df_rec_3)

df_rec = pd.concat([df_rec_1, df_rec_2, df_rec_3],  ignore_index=True)
display(df_rec)

df_rec_pivot = df_rec.pivot_table(index=["Repetition", "Dataset", "Métrica"], columns="Imputer", values="score")
df_rec_pivot_reset = df_rec_pivot.reset_index()
df_rec_pivot_reset.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df_rec_pivot_reset.columns.values]
df_rec = df_AUC_pivot_reset[['KNN', 'LPMD', 'LPMD2', 'MICE', 'Mean', 'PMIVAE', 'SAEI']]
df_rec

     Repetition  Dataset Imputer Métrica     score
0             0        1    MICE  Recall  0.666667
1             1        1    MICE  Recall  0.571429
2             2        1    MICE  Recall  0.571429
3             3        1    MICE  Recall  0.714286
4             4        1    MICE  Recall  0.500000
..          ...      ...     ...     ...       ...
410           0        4   LPMD2  Recall  0.692308
411           1        4   LPMD2  Recall  0.692308
412           2        4   LPMD2  Recall  0.846154
413           3        4   LPMD2  Recall  0.571429
414           4        4   LPMD2  Recall  0.714286

[140 rows x 5 columns]

     Repetition  Dataset Imputer Métrica     score
0             0        1    MICE  Recall  0.666667
1             1        1    MICE  Recall  0.714286
2             2        1    MICE  Recall  0.428571
3             3        1    MICE  Recall  0.857143
4             4        1    MICE  Recall  0.833333
..          ...      ...     ...     ...       ...
410           0        4   LPMD2  Recall  0.538462
411           1        4   LPMD2  Recall  0.384615
412           2        4   LPMD2  Recall  0.769231
413           3        4   LPMD2  Recall  0.500000
414           4        4   LPMD2  Recall  0.571429

[140 rows x 5 columns]

     Repetition  Dataset Imputer Métrica     score
0             0        1    MICE  Recall  0.666667
1             1        1    MICE  Recall  0.142857
2             2        1    MICE  Recall  0.714286
3             3        1    MICE  Recall  0.714286
4             4        1    MICE  Recall  0.833333
..          ...      ...     ...     ...       ...
410           0        4   LPMD2  Recall  0.538462
411           1        4   LPMD2  Recall  0.384615
412           2        4   LPMD2  Recall  0.461538
413           3        4   LPMD2  Recall  0.571429
414           4        4   LPMD2  Recall  0.500000

[140 rows x 5 columns]

     Repetition  Dataset Imputer Métrica     score
0             0        1    MICE  Recall  0.666667
1             1        1    MICE  Recall  0.571429
2             2        1    MICE  Recall  0.571429
3             3        1    MICE  Recall  0.714286
4             4        1    MICE  Recall  0.500000
..          ...      ...     ...     ...       ...
415           0        4   LPMD2  Recall  0.538462
416           1        4   LPMD2  Recall  0.384615
417           2        4   LPMD2  Recall  0.461538
418           3        4   LPMD2  Recall  0.571429
419           4        4   LPMD2  Recall  0.500000

[420 rows x 5 columns]

         KNN      LPMD     LPMD2      MICE      Mean    PMIVAE      SAEI
0   0.793144  0.743203  0.721631  0.719858  0.774823  0.729019  0.674941
1   0.835796  0.843044  0.824308  0.840312  0.844221  0.843696  0.854182
2   0.774610  0.777286  0.628392  0.773463  0.775513  0.774262  0.781056
3   0.763889  0.735043  0.820513  0.770299  0.740385  0.727564  0.736111
4   0.629544  0.633129  0.642857  0.601895  0.599334  0.620328  0.590886
5   0.836126  0.833573  0.820447  0.838139  0.836295  0.832976  0.829934
6   0.715001  0.725894  0.608204  0.729369  0.714636  0.713715  0.732296
7   0.740385  0.744658  0.626068  0.741453  0.735043  0.752137  0.702991
8   0.735279  0.760369  0.672555  0.734255  0.796723  0.738095  0.672299
9   0.840928  0.836333  0.850383  0.844962  0.850179  0.842853  0.840541
10  0.726958  0.725721  0.677725  0.741068  0.733272  0.729931  0.731667
11  0.629274  0.661859  0.558226  0.642628  0.665598  0.580128  0.683761
12  0.716334  0.718126  0.683308  0.733743  0.699181  0.700461  0.677675
13  0.859569  0.841791  0.830181  0.845201  0.853648  0.852659  0.849176
14  0.731639  0.730556  0.572554  0.738330  0.728346  0.725393  0.728477
15  0.750518  0.703934  0.698758  0.744306  0.697205  0.691511  0.772257
16  0.650538  0.721027  0.695042  0.686081  0.729092  0.733274  0.665173
17  0.840955  0.846000  0.814367  0.844989  0.843549  0.847446  0.853208
18  0.769078  0.762884  0.646174  0.778564  0.765828  0.760849  0.758718
19  0.741201  0.669772  0.719462  0.716874  0.643375  0.710145  0.746377

In [34]:
df_rec.to_csv("df_REC_real_datasets.csv", index=False)

# Refazendo procedimento para Specificity

In [35]:
df_spe_1 = df_spe[["Repetition", "Dataset", "Imputer", "Métrica", "SVM"]]
df_spe_1 = df_spe_1.rename(columns={"SVM": "score"})
display(df_spe_1)

df_spe_2 = df_spe[["Repetition", "Dataset", "Imputer", "Métrica", "RF"]]
df_spe_2 = df_spe_2.rename(columns={"RF": "score"})
display(df_spe_2)

df_spe_3 = df_spe[["Repetition", "Dataset", "Imputer", "Métrica", "GB"]]
df_spe_3 = df_spe_3.rename(columns={"GB": "score"})
display(df_spe_3)

df_spe = pd.concat([df_spe_1, df_spe_2, df_spe_3],  ignore_index=True)
display(df_spe)

df_spe_pivot = df_spe.pivot_table(index=["Repetition", "Dataset", "Métrica"], columns="Imputer", values="score")
df_spe_pivot_reset = df_spe_pivot.reset_index()
df_spe_pivot_reset.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df_spe_pivot_reset.columns.values]
df_spe = df_spe_pivot_reset[['KNN', 'LPMD', 'LPMD2', 'MICE', 'Mean', 'PMIVAE', 'SAEI']]
df_spe

     Repetition  Dataset Imputer      Métrica     score
10            0        4  PMIVAE  Specificity  0.666667
11            1        4  PMIVAE  Specificity  0.833333
12            2        4  PMIVAE  Specificity  0.458333
13            3        4  PMIVAE  Specificity  0.652174
14            4        4  PMIVAE  Specificity  0.565217
..          ...      ...     ...          ...       ...
405           0        3  PMIVAE  Specificity  0.640884
406           1        3  PMIVAE  Specificity  0.596685
407           2        3  PMIVAE  Specificity  0.679558
408           3        3  PMIVAE  Specificity  0.722222
409           4        3  PMIVAE  Specificity  0.711111

[140 rows x 5 columns]

     Repetition  Dataset Imputer      Métrica     score
10            0        4  PMIVAE  Specificity  0.791667
11            1        4  PMIVAE  Specificity  0.791667
12            2        4  PMIVAE  Specificity  0.500000
13            3        4  PMIVAE  Specificity  0.608696
14            4        4  PMIVAE  Specificity  0.521739
..          ...      ...     ...          ...       ...
405           0        3  PMIVAE  Specificity  0.701657
406           1        3  PMIVAE  Specificity  0.662983
407           2        3  PMIVAE  Specificity  0.635359
408           3        3  PMIVAE  Specificity  0.677778
409           4        3  PMIVAE  Specificity  0.700000

[140 rows x 5 columns]

     Repetition  Dataset Imputer      Métrica     score
10            0        4  PMIVAE  Specificity  0.791667
11            1        4  PMIVAE  Specificity  0.833333
12            2        4  PMIVAE  Specificity  0.458333
13            3        4  PMIVAE  Specificity  0.739130
14            4        4  PMIVAE  Specificity  0.565217
..          ...      ...     ...          ...       ...
405           0        3  PMIVAE  Specificity  0.690608
406           1        3  PMIVAE  Specificity  0.624309
407           2        3  PMIVAE  Specificity  0.662983
408           3        3  PMIVAE  Specificity  0.655556
409           4        3  PMIVAE  Specificity  0.738889

[140 rows x 5 columns]

     Repetition  Dataset Imputer      Métrica     score
0             0        4  PMIVAE  Specificity  0.666667
1             1        4  PMIVAE  Specificity  0.833333
2             2        4  PMIVAE  Specificity  0.458333
3             3        4  PMIVAE  Specificity  0.652174
4             4        4  PMIVAE  Specificity  0.565217
..          ...      ...     ...          ...       ...
415           0        3  PMIVAE  Specificity  0.690608
416           1        3  PMIVAE  Specificity  0.624309
417           2        3  PMIVAE  Specificity  0.662983
418           3        3  PMIVAE  Specificity  0.655556
419           4        3  PMIVAE  Specificity  0.738889

[420 rows x 5 columns]

         KNN      LPMD     LPMD2      MICE      Mean    PMIVAE      SAEI
0   0.585106  0.680851  0.570922  0.592199  0.624113  0.606383  0.670213
1   0.768024  0.775233  0.734521  0.786260  0.779474  0.784139  0.793469
2   0.679558  0.662983  0.524862  0.703499  0.677716  0.677716  0.705341
3   0.791667  0.750000  0.819444  0.750000  0.722222  0.750000  0.722222
4   0.702509  0.677419  0.698925  0.716846  0.684588  0.702509  0.695341
5   0.750743  0.768153  0.714650  0.757962  0.766879  0.761783  0.769851
6   0.624309  0.642726  0.429098  0.627993  0.642726  0.627993  0.631676
7   0.888889  0.875000  0.888889  0.861111  0.847222  0.819444  0.833333
8   0.691756  0.666667  0.555556  0.724014  0.695341  0.673835  0.702509
9   0.740127  0.749045  0.731210  0.741401  0.742675  0.748195  0.742251
10  0.681400  0.674033  0.591160  0.681400  0.661142  0.659300  0.666667
11  0.500000  0.513889  0.513889  0.527778  0.513889  0.472222  0.569444
12  0.591398  0.598566  0.505376  0.587814  0.541219  0.551971  0.594982
13  0.768577  0.772399  0.754140  0.773248  0.780042  0.777919  0.776221
14  0.648148  0.685185  0.394444  0.685185  0.681481  0.685185  0.672222
15  0.695652  0.666667  0.710145  0.637681  0.608696  0.666667  0.695652
16  0.670251  0.673835  0.620072  0.627240  0.616487  0.602151  0.648746
17  0.757537  0.777070  0.673885  0.752866  0.758811  0.765605  0.743524
18  0.712963  0.716667  0.548148  0.694444  0.720370  0.716667  0.700000
19  0.623188  0.565217  0.739130  0.637681  0.478261  0.550725  0.623188

In [36]:
df_spe.to_csv("df_SPE_real_datasets.csv", index=False)

# Juntando as três métricas para aumentar o volume de dados

In [111]:
df_real_datasets = pd.concat([df_AUC, df_rec, df_spe], ignore_index=True)

df_real_datasets

         KNN      LPMD     LPMD2      MICE      Mean    PMIVAE      SAEI
0   0.793144  0.743203  0.721631  0.719858  0.774823  0.729019  0.674941
1   0.835796  0.843044  0.824308  0.840312  0.844221  0.843696  0.854182
2   0.774610  0.777286  0.628392  0.773463  0.775513  0.774262  0.781056
3   0.763889  0.735043  0.820513  0.770299  0.740385  0.727564  0.736111
4   0.629544  0.633129  0.642857  0.601895  0.599334  0.620328  0.590886
5   0.836126  0.833573  0.820447  0.838139  0.836295  0.832976  0.829934
6   0.715001  0.725894  0.608204  0.729369  0.714636  0.713715  0.732296
7   0.740385  0.744658  0.626068  0.741453  0.735043  0.752137  0.702991
8   0.735279  0.760369  0.672555  0.734255  0.796723  0.738095  0.672299
9   0.840928  0.836333  0.850383  0.844962  0.850179  0.842853  0.840541
10  0.726958  0.725721  0.677725  0.741068  0.733272  0.729931  0.731667
11  0.629274  0.661859  0.558226  0.642628  0.665598  0.580128  0.683761
12  0.716334  0.718126  0.683308  0.733743  0.699181  0.700461  0.677675
13  0.859569  0.841791  0.830181  0.845201  0.853648  0.852659  0.849176
14  0.731639  0.730556  0.572554  0.738330  0.728346  0.725393  0.728477
15  0.750518  0.703934  0.698758  0.744306  0.697205  0.691511  0.772257
16  0.650538  0.721027  0.695042  0.686081  0.729092  0.733274  0.665173
17  0.840955  0.846000  0.814367  0.844989  0.843549  0.847446  0.853208
18  0.769078  0.762884  0.646174  0.778564  0.765828  0.760849  0.758718
19  0.741201  0.669772  0.719462  0.716874  0.643375  0.710145  0.746377
20  0.793144  0.743203  0.721631  0.719858  0.774823  0.729019  0.674941
21  0.835796  0.843044  0.824308  0.840312  0.844221  0.843696  0.854182
22  0.774610  0.777286  0.628392  0.773463  0.775513  0.774262  0.781056
23  0.763889  0.735043  0.820513  0.770299  0.740385  0.727564  0.736111
24  0.629544  0.633129  0.642857  0.601895  0.599334  0.620328  0.590886
25  0.836126  0.833573  0.820447  0.838139  0.836295  0.832976  0.829934
26  0.715001  0.725894  0.608204  0.729369  0.714636  0.713715  0.732296
27  0.740385  0.744658  0.626068  0.741453  0.735043  0.752137  0.702991
28  0.735279  0.760369  0.672555  0.734255  0.796723  0.738095  0.672299
29  0.840928  0.836333  0.850383  0.844962  0.850179  0.842853  0.840541
30  0.726958  0.725721  0.677725  0.741068  0.733272  0.729931  0.731667
31  0.629274  0.661859  0.558226  0.642628  0.665598  0.580128  0.683761
32  0.716334  0.718126  0.683308  0.733743  0.699181  0.700461  0.677675
33  0.859569  0.841791  0.830181  0.845201  0.853648  0.852659  0.849176
34  0.731639  0.730556  0.572554  0.738330  0.728346  0.725393  0.728477
35  0.750518  0.703934  0.698758  0.744306  0.697205  0.691511  0.772257
36  0.650538  0.721027  0.695042  0.686081  0.729092  0.733274  0.665173
37  0.840955  0.846000  0.814367  0.844989  0.843549  0.847446  0.853208
38  0.769078  0.762884  0.646174  0.778564  0.765828  0.760849  0.758718
39  0.741201  0.669772  0.719462  0.716874  0.643375  0.710145  0.746377
40  0.585106  0.680851  0.570922  0.592199  0.624113  0.606383  0.670213
41  0.768024  0.775233  0.734521  0.786260  0.779474  0.784139  0.793469
42  0.679558  0.662983  0.524862  0.703499  0.677716  0.677716  0.705341
43  0.791667  0.750000  0.819444  0.750000  0.722222  0.750000  0.722222
44  0.702509  0.677419  0.698925  0.716846  0.684588  0.702509  0.695341
45  0.750743  0.768153  0.714650  0.757962  0.766879  0.761783  0.769851
46  0.624309  0.642726  0.429098  0.627993  0.642726  0.627993  0.631676
47  0.888889  0.875000  0.888889  0.861111  0.847222  0.819444  0.833333
48  0.691756  0.666667  0.555556  0.724014  0.695341  0.673835  0.702509
49  0.740127  0.749045  0.731210  0.741401  0.742675  0.748195  0.742251
50  0.681400  0.674033  0.591160  0.681400  0.661142  0.659300  0.666667
51  0.500000  0.513889  0.513889  0.527778  0.513889  0.472222  0.569444
52  0.591398  0.598566  0.505376  0.587814  0.541219  0.551971  0.594982
53  0.768577  0.772399  0.754140  0.773248  0.780042  0.777919  0.776221
54  0.648148  0.685185  0.394444  0.685185  0.681481  0.685185  0.672222
55  0.695652  0.666667  0.710145  0.637681  0.608696  0.666667  0.695652
56  0.670251  0.673835  0.620072  0.627240  0.616487  0.602151  0.648746
57  0.757537  0.777070  0.673885  0.752866  0.758811  0.765605  0.743524
58  0.712963  0.716667  0.548148  0.694444  0.720370  0.716667  0.700000
59  0.623188  0.565217  0.739130  0.637681  0.478261  0.550725  0.623188

In [113]:
df_real_datasets.to_csv("all_results_real_datasets.csv", index=False)